In [ ]:
import numpy as np

In [45]:
# Create an 1-D array
arr = np.array([1,2,3])
#print(arr)

# Create a 2-D array
arr2d = np.array([[1,2,3], [1,2,3]])
print(arr2d)

#2d Array functions

arr2d2 = np.insert(arr2d, 0, [4,5,6], axis=0)
print(arr2d2)

arr2d3 = np.insert(arr2d, 1, [7,8], axis=1)
print(arr2d3)

rm = np.delete(arr2d3, [1], axis=0)
print(rm)

[[1 2 3]
 [1 2 3]]
[[4 5 6]
 [1 2 3]
 [1 2 3]]
[[1 7 2 3]
 [1 8 2 3]]
[[1 7 2 3]]


In [52]:
# length of an array
print(arr2d)
print(len(arr2d))
print(len(arr2d[0]))

[[1 2 3]
 [1 2 3]]
2
3


In [54]:
# Traversing through 2d array
for rid in range(0, len(arr2d)):
    print(rid)
    for cid in range(0, len(arr2d[0])):
        print(rid, cid)

0
0 0
0 1
0 2
1
1 0
1 1
1 2


In [63]:
# Searching for an item in the array
[1,2,3].index(3)

print(arr2d3)
# Searching an element in a 2d array is done using traversal for linear search algorithm
for rid in range(0, len(arr2d3)):
    for cid in range(0, len(arr2d3[0])):
        if arr2d3[rid][cid] == 8:
            print(rid, cid)
        else:
            print('element not present')


[[1 7 2 3]
 [1 8 2 3]]
element not present
element not present
element not present
element not present
element not present
1 1
element not present
element not present


In [67]:
# Deleting a row/column in an array (in numpy arrays, it returns a new array with deleted row/column)
# Time/space complexity of modification of array can be full and not O(1) as it creates a new array 

# Row delete
arr2d4 = np.delete(arr2d3, 0, axis=0)
print(arr2d4)

# Column delete
arr2d4 = np.delete(arr2d3, 0, axis=1)
print(arr2d4)

[[1 8 2 3]]
[[7 2 3]
 [8 2 3]]
