In [9]:
import numpy as np
l = [[1,2,3],[4,5,6],[7,8,9]]
l2 = [[2,4,6],[8,10,12],[14,16,18]]

In [10]:
# Numpy array functions operations
m = np.array(l)
n = np.array(l2)

print(m)
print(np.sum(m))

# Row sum
print(np.sum(m, axis=0))

# Column sum
print(np.sum(m, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [11]:
# Add two arrays (Matrices)
o = np.add(m,n)
print(o)

# Add two arrays (Matrices)
p = np.subtract(m,n)
print(p)

# Add two arrays (Matrices)
q = np.multiply(m,n)
print(q)

# Add two arrays (Matrices)
r = np.divide(m,n)
print(r)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [5]:
# All the above arithmatic operations can be performed using arithmatic symbols with numpy arrays
sum_arr = m + n
sum_arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [12]:
subtract_arr = n - m
subtract_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
m * n

array([[  2,   8,  18],
       [ 32,  50,  72],
       [ 98, 128, 162]])

In [14]:
m / n

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [15]:
m % n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
2*m + n/2

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])