In [7]:
import numpy as np
myList2D = [[1,2,3],[4,5,6],[7,8,9]] 
#myList2D2 = [[1,2,3,4],[4,5,6,7],[7,8,9,10]] 

arr = np.array(myList2D)
#arr = np.array(myList2D2)

print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# How I did but time complexity is O(n**2)
sum = 0
for rid in range(0, len(arr)):
    for cid in range(0, len(arr[0])):
        print(rid, cid)
        if rid == cid:
            val = arr[rid][cid]
            sum += val
            print(sum)
            break
print(sum)

0 0
1
1 0
1 1
6
2 0
2 1
2 2
15
15


In [25]:
# Efficient way
sum = 0
for i in range(0, len(arr)):
    sum = sum + arr[i][i]

print(sum)
print(9**0.5)

15
3.0
