In [ ]:
import numpy as np
myList = [7, 1, 3, 4, 9, 5]
arr = np.array(myList)
print(arr)

In [ ]:
# sorting a list/array using list

print(myList)
idx1 = 0
num1 = 0
list_tg = []

for idx2, num2 in enumerate(arr, 0):
    
    print(idx2, num2)
    print(idx1, num1)

    if idx2 == 0:
        list_tg.append(num2)
        num1 = num2
    
    elif num2 >= num1:
        list_tg.append(num2)
        num1 = num2
    else:
        print(len(list_tg))
        for idx_hist, i in enumerate(list_tg, 0):
            print(idx_hist, i)
            if i > num2:
                list_tg.insert(idx_hist, num2)
                break
            
        num1 = num1
    
    idx1 = idx2
    print(list_tg)
    

In [27]:
# Sorting a list/array using an numpy array

print(myList)
idx1 = 0
num1 = 0
list_tg = []
np_arr = np.array([])
print(np_arr)

for idx2, num2 in enumerate(arr, 0):
    
    print(idx2, num2)
    print(idx1, num1)

    if idx2 == 0:
        np_arr = np.append(np_arr, num2)
        num1 = num2
    
    elif num2 >= num1:
        np_arr = np.append(np_arr, num2)
        num1 = num2
    else:
        print(len(np_arr))
        for idx_hist, i in enumerate(np_arr, 0):
            print(idx_hist, i)
            if i > num2:
                np_arr = np.insert(np_arr, idx_hist, num2)
                break
            
        num1 = num1
    
    idx1 = idx2
    print(np_arr)
    

[7, 1, 3, 4, 9, 5]
[]
0 7
0 0
[7.]
1 1
0 7
1
0 7.0
[1. 7.]
2 3
1 7
2
0 1.0
1 7.0
[1. 3. 7.]
3 4
2 7
3
0 1.0
1 3.0
2 7.0
[1. 3. 4. 7.]
4 9
3 7
[1. 3. 4. 7. 9.]
5 5
4 9
5
0 1.0
1 3.0
2 4.0
3 7.0
[1. 3. 4. 5. 7. 9.]
