In [9]:
import numpy as np
l = [[1,2,3],[4,5,6],[7,8,9]]
l2 = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
# Numpy array functions operations
m = np.array(l)
n = np.array(l2)

print(m)
print(np.sum(m))

# Row sum
print(np.sum(m, axis=0))

# Column sum
print(np.sum(m, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


In [17]:
# Add two arrays (Matrices)
o = np.add(m,n)
print(o)

# Add two arrays (Matrices)
p = np.subtract(m,n)
print(p)

# Add two arrays (Matrices)
q = np.multiply(m,n)
print(q)

# Add two arrays (Matrices)
r = np.divide(m,n)
print(r)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
